# File: v3io.yaml

#logLevel: debug

# NGINX server address:PORT
webApiEndpoint: "192.168.224.158:8085"

# V3IO container ID or Name
container: "tsdb"

# Path in the container (default, should be override by test)
tablePath: "tsdb-0"

# Logging level. Valid values: debug,info,warn,error (Default: info)
verbose: "debug"

# Default timeout 10 seconds
#timeout: 10

workers: 1
qryWorkers: 8
#batchSize: 64

username: "admin"
password: "24tango"

#performance:
#  reportOnShutdown: true
#  output: "stderr"
#  reportPeriodically: true
#  reportInterval: 10
